### PR TITLE
Fix depricated warning

### PR DESCRIPTION
**Pull request by frank-bee**
Signed-off-by: Bernhardt Frank (GS/PJ-TOP98) <Frank.Bernhardt@de.bosch.com>

### CODE REVIEW

**Comment by snovikov** [comment]
@frank-bee I think one issue is that you have pdated README.md, but `versions.tf` stayed the same - its for `terraform-docs` check.

**Comment by snovikov** [comment]
@frank-bee another one is that we have a bug in linting. Makefile uses `TF_VERSION     = 0.13.7`, but github actions uses latest TF (see https://github.com/Flaconi/terraform-aws-bastion-ssm-iam/blob/master/.github/workflows/linting.yml#L23).

After running

```
$ terraform fmt -recursive
main.tf
$ terraform version
Terraform v1.1.9
```

I got following:
```
diff --git a/main.tf b/main.tf
index 85aa910..1895873 100644
--- a/main.tf
+++ b/main.tf
@@ -90,7 +90,7 @@ resource "aws_autoscaling_group" "this" {
     propagate_at_launch = true
   }
 
-  dynamic tag {
+  dynamic "tag" {
     for_each = var.tags
     content {
       key                 = tag.value["key"]
```

Feel free to update the `Makefile` TF version to `1.0+`

**Review by snovikov — CHANGES_REQUESTED** [review]
I have left comments above

**Comment by frank-bee** [comment]
ok , will update this as soon as I find, maybe tomorrow!

**Comment by snovikov** [comment]
@frank-bee unfortunately there is a problem with using `.terraform.lock.hcl` - it put too strict restrictions on provider version.
In case if place where we use this module have other version restrictions it could cause a lot of problems.

E.g. I have restriction like `hashicorp/aws ~> 4.22` in my `terragrunt` configuration and it casuing me this error:

```
╷
│ Error: Failed to query available provider packages
│ 
│ Could not retrieve the list of available versions for provider
│ hashicorp/aws: locked provider registry.terraform.io/hashicorp/aws 4.21.0
│ does not match configured version constraint ~> 4.22; must use terraform
│ init -upgrade to allow selection of new versions
╵
```

In fact, I cannot find any module, where `.terraform.lock.hcl` was included - in most used ones, like
- https://github.com/terraform-aws-modules/terraform-aws-ec2-instance
- https://github.com/terraform-aws-modules/terraform-aws-s3-bucket

Please remove `.terraform.lock.hcl` and add it to `.gitignore`.

**Review by snovikov — CHANGES_REQUESTED** [review]
Please read my comment above.

**Comment by snovikov** [comment]
@frank-bee Unfortunately I cannot push into your branch to fix it, as it is in you repository.

**Comment by frank-bee** [comment]
@snovikov sorry I am on holiday and check my mails only from time to time

**Review by snovikov — APPROVED** [review]

**Pull request merged**
